name: '{{ project_name }}'
version: '1.0.0'
config-version: 2

profile: '{{ project_name }}'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  +transient: false
  +persist_docs:
    relation: true
    columns: true